### ISSUE TITLE
x64编译问题

### ISSUE THREAD

**Issue by mensong** [weolar/blinkgc#3]
x64编译的时候出现一大堆错误，经过一一解决后，只剩下“pushAllRegisters”这个问题没有解决：
1>SafePoint.obj : error LNK2019: 无法解析的外部符号 pushAllRegisters，该符号在函数 "public: void __cdecl blink::SafePointBarrier::enterSafePoint(class blink::ThreadState *)" (?enterSafePoint@SafePointBarrier@blink@@QEAAXPEAVThreadState@2@@Z) 中被引用
1>C:\Users\Administrator\Desktop\blinkgc-master\x64\Debug\blinkgc.exe : fatal error LNK1120: 1 个无法解析的外部命令
我看到“platform\heap\asm”目录里有这些文件里定义了“pushAllRegisters”：
SaveRegisters_arm.S
SaveRegisters_arm64.S
SaveRegisters_mips.S
SaveRegisters_mips64.S
SaveRegisters_x86.asm
我该使用哪一个进行内联编译呢？

**Comment by weolar** [comment]
我没编译过X64。这里貌似需要一个SaveRegisters_x64.asm。你可以手写一个

**Comment by weolar** [comment]
貌似SaveRegisters_x86.asm这个就是。
我也不清楚为什么谷歌会叫这名字

**Comment by mensong** [comment]
发现了，在SaveRegisters_x86.asm文件里有一段是x64的。
